name: auto build and test
on:
  pull_request:
    branches: [main]
env:
  RUST_TOOLCHAIN: nightly-2022-04-09
  CARGO_TERM_COLOR: always
jobs:
  run-test:
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust toolchain@v1
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: rustfmt, clippy, llvm-tools-preview
      - name: Run rust clippy check
        run: |
          # If new CI checks are added, the one with `--locked` must be run first.
          cargo clippy --all-targets --locked -- -D warnings
      - name: Run rust test with coverage
        run: |
          cargo llvm-cov nextest --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v2
